map-key-parameter:
  wait: wait
  steps: steps
  next: next
  total: total
  type: type
  interval: interval
  exchange: exchange
  subExch: subExch
  name: name
  market: market
  ticker: ticker
  symbol: symbol
  date: date
  time: time
  open: open
  high: high
  low: low    
  close: close
  adjClose: adjClose
  prevClose: prevClose
  volume: volume
  percentChange: percentChange
  year: year
  month: month
  day: day
  weekOfYear: weekOfYear
  yearForWeek: yearForWeek
  dayOfYear: dayOfYear
  dayOfWeek: dayOfWeek  
  fromDate: fromDate
  fromYear: fromYear
  fromMonth: fromMonth
  fromDay: fromDay
  fromWeekOfYear: fromWeekOfYear
  fromDayOfWeek: fromDayOfWeek
  fromYearForWeek: fromYearForWeek
  toDate: toDate
  toYear: toYear
  toMonth: toMonth
  toDay: toDay
  toWeekOfYear: toWeekOfYear
  toDayOfWeek: toDayOfWeek
  toYearForWeek: toYearForWeek 
  suffixHigh: high
  suffixLow: low
  hHigh: hHigh
  hLow: hLow
  hHighD: hHighD
  hLowD: hLowD
  newHigh: newHigh
  newLow: newLow
  exchangeN: exchangeN
  country: country
  currency: currency
  industry: industry
  sector: sector
  beta: beta
  FPE: FPE
  PB: PB
  sharesO: sharesO
  mCap: mCap
  dataType: dataType
  dataSource: dataSource
  directory: directory
  fileName: fileName
  from: from
  hTotal: hTotal
  hFirstD: hFirstD
  hLastD: hLastD
  lastP: lastP
  ind: ind
  inst: inst
  limit: limit
  save: save
  group: group
  yahooIndustry: y
  format: format
  length: length